// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protob/eddsa-keygen.proto

package keygen

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
// Represents a BROADCAST message sent during Round 1 of the EDDSA TSS keygen protocol.
type EDDSAKGRound1Message struct {
	Commitment           []byte   `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EDDSAKGRound1Message) Reset()         { *m = EDDSAKGRound1Message{} }
func (m *EDDSAKGRound1Message) String() string { return proto.CompactTextString(m) }
func (*EDDSAKGRound1Message) ProtoMessage()    {}
func (*EDDSAKGRound1Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_270212b40d652dfc, []int{0}
}

func (m *EDDSAKGRound1Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EDDSAKGRound1Message.Unmarshal(m, b)
}
func (m *EDDSAKGRound1Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EDDSAKGRound1Message.Marshal(b, m, deterministic)
}
func (m *EDDSAKGRound1Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EDDSAKGRound1Message.Merge(m, src)
}
func (m *EDDSAKGRound1Message) XXX_Size() int {
	return xxx_messageInfo_EDDSAKGRound1Message.Size(m)
}
func (m *EDDSAKGRound1Message) XXX_DiscardUnknown() {
	xxx_messageInfo_EDDSAKGRound1Message.DiscardUnknown(m)
}

var xxx_messageInfo_EDDSAKGRound1Message proto.InternalMessageInfo

func (m *EDDSAKGRound1Message) GetCommitment() []byte {
	if m != nil {
		return m.Commitment
	}
	return nil
}

//
// Represents a P2P message sent to each party during Round 2 of the EDDSA TSS keygen protocol.
type EDDSAKGRound2Message1 struct {
	Share                []byte   `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EDDSAKGRound2Message1) Reset()         { *m = EDDSAKGRound2Message1{} }
func (m *EDDSAKGRound2Message1) String() string { return proto.CompactTextString(m) }
func (*EDDSAKGRound2Message1) ProtoMessage()    {}
func (*EDDSAKGRound2Message1) Descriptor() ([]byte, []int) {
	return fileDescriptor_270212b40d652dfc, []int{1}
}

func (m *EDDSAKGRound2Message1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EDDSAKGRound2Message1.Unmarshal(m, b)
}
func (m *EDDSAKGRound2Message1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EDDSAKGRound2Message1.Marshal(b, m, deterministic)
}
func (m *EDDSAKGRound2Message1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EDDSAKGRound2Message1.Merge(m, src)
}
func (m *EDDSAKGRound2Message1) XXX_Size() int {
	return xxx_messageInfo_EDDSAKGRound2Message1.Size(m)
}
func (m *EDDSAKGRound2Message1) XXX_DiscardUnknown() {
	xxx_messageInfo_EDDSAKGRound2Message1.DiscardUnknown(m)
}

var xxx_messageInfo_EDDSAKGRound2Message1 proto.InternalMessageInfo

func (m *EDDSAKGRound2Message1) GetShare() []byte {
	if m != nil {
		return m.Share
	}
	return nil
}

//
// Represents a BROADCAST message sent to each party during Round 2 of the EDDSA TSS keygen protocol.
type EDDSAKGRound2Message2 struct {
	DeCommitment         [][]byte `protobuf:"bytes,1,rep,name=de_commitment,json=deCommitment,proto3" json:"de_commitment,omitempty"`
	ProofAlphaX          []byte   `protobuf:"bytes,2,opt,name=proof_alpha_x,json=proofAlphaX,proto3" json:"proof_alpha_x,omitempty"`
	ProofAlphaY          []byte   `protobuf:"bytes,3,opt,name=proof_alpha_y,json=proofAlphaY,proto3" json:"proof_alpha_y,omitempty"`
	ProofT               []byte   `protobuf:"bytes,4,opt,name=proof_t,json=proofT,proto3" json:"proof_t,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EDDSAKGRound2Message2) Reset()         { *m = EDDSAKGRound2Message2{} }
func (m *EDDSAKGRound2Message2) String() string { return proto.CompactTextString(m) }
func (*EDDSAKGRound2Message2) ProtoMessage()    {}
func (*EDDSAKGRound2Message2) Descriptor() ([]byte, []int) {
	return fileDescriptor_270212b40d652dfc, []int{2}
}

func (m *EDDSAKGRound2Message2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EDDSAKGRound2Message2.Unmarshal(m, b)
}
func (m *EDDSAKGRound2Message2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EDDSAKGRound2Message2.Marshal(b, m, deterministic)
}
func (m *EDDSAKGRound2Message2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EDDSAKGRound2Message2.Merge(m, src)
}
func (m *EDDSAKGRound2Message2) XXX_Size() int {
	return xxx_messageInfo_EDDSAKGRound2Message2.Size(m)
}
func (m *EDDSAKGRound2Message2) XXX_DiscardUnknown() {
	xxx_messageInfo_EDDSAKGRound2Message2.DiscardUnknown(m)
}

var xxx_messageInfo_EDDSAKGRound2Message2 proto.InternalMessageInfo

func (m *EDDSAKGRound2Message2) GetDeCommitment() [][]byte {
	if m != nil {
		return m.DeCommitment
	}
	return nil
}

func (m *EDDSAKGRound2Message2) GetProofAlphaX() []byte {
	if m != nil {
		return m.ProofAlphaX
	}
	return nil
}

func (m *EDDSAKGRound2Message2) GetProofAlphaY() []byte {
	if m != nil {
		return m.ProofAlphaY
	}
	return nil
}

func (m *EDDSAKGRound2Message2) GetProofT() []byte {
	if m != nil {
		return m.ProofT
	}
	return nil
}

func init() {
	proto.RegisterType((*EDDSAKGRound1Message)(nil), "EDDSAKGRound1Message")
	proto.RegisterType((*EDDSAKGRound2Message1)(nil), "EDDSAKGRound2Message1")
	proto.RegisterType((*EDDSAKGRound2Message2)(nil), "EDDSAKGRound2Message2")
}

func init() {
	proto.RegisterFile("protob/eddsa-keygen.proto", fileDescriptor_270212b40d652dfc)
}

var fileDescriptor_270212b40d652dfc = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xd2, 0x4f, 0x4d, 0x49, 0x29, 0x4e, 0xd4, 0xcd, 0x4e, 0xad, 0x4c, 0x4f, 0xcd, 0xd3,
	0x03, 0x8b, 0x29, 0x99, 0x71, 0x89, 0xb8, 0xba, 0xb8, 0x04, 0x3b, 0x7a, 0xbb, 0x07, 0xe5, 0x97,
	0xe6, 0xa5, 0x18, 0xfa, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x0a, 0xc9, 0x71, 0x71, 0x25, 0xe7,
	0xe7, 0xe6, 0x66, 0x96, 0xe4, 0xa6, 0xe6, 0x95, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0x21,
	0x89, 0x28, 0xe9, 0x72, 0x89, 0x22, 0xeb, 0x33, 0x82, 0xea, 0x33, 0x14, 0x12, 0xe1, 0x62, 0x2d,
	0xce, 0x48, 0x2c, 0x4a, 0x85, 0xea, 0x81, 0x70, 0x94, 0xe6, 0x32, 0x62, 0x57, 0x6f, 0x24, 0xa4,
	0xcc, 0xc5, 0x9b, 0x92, 0x1a, 0x8f, 0x62, 0x17, 0xb3, 0x06, 0x4f, 0x10, 0x4f, 0x4a, 0xaa, 0x33,
	0x5c, 0x4c, 0x48, 0x89, 0x8b, 0xb7, 0xa0, 0x28, 0x3f, 0x3f, 0x2d, 0x3e, 0x31, 0xa7, 0x20, 0x23,
	0x31, 0xbe, 0x42, 0x82, 0x09, 0x6c, 0x38, 0x37, 0x58, 0xd0, 0x11, 0x24, 0x16, 0x81, 0xae, 0xa6,
	0x52, 0x82, 0x19, 0x5d, 0x4d, 0xa4, 0x90, 0x38, 0x17, 0x3b, 0x44, 0x4d, 0x89, 0x04, 0x0b, 0x58,
	0x96, 0x0d, 0xcc, 0x0d, 0x71, 0xe2, 0x8b, 0xe2, 0x01, 0x07, 0x8e, 0x3e, 0x24, 0x70, 0x92, 0xd8,
	0xc0, 0xa1, 0x63, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x94, 0x88, 0x31, 0x96, 0x3a, 0x01, 0x00,
	0x00,
}
