// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protob/eddsa-resharing.proto

package resharing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
// The Round 1 data is broadcast to peers of the New Committee in this message.
type EDDSADGRound1Message struct {
	EddsaPubX            []byte   `protobuf:"bytes,1,opt,name=eddsa_pub_x,json=eddsaPubX,proto3" json:"eddsa_pub_x,omitempty"`
	EddsaPubY            []byte   `protobuf:"bytes,2,opt,name=eddsa_pub_y,json=eddsaPubY,proto3" json:"eddsa_pub_y,omitempty"`
	VCommitment          []byte   `protobuf:"bytes,3,opt,name=v_commitment,json=vCommitment,proto3" json:"v_commitment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EDDSADGRound1Message) Reset()         { *m = EDDSADGRound1Message{} }
func (m *EDDSADGRound1Message) String() string { return proto.CompactTextString(m) }
func (*EDDSADGRound1Message) ProtoMessage()    {}
func (*EDDSADGRound1Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd99ebe69a0b0962, []int{0}
}

func (m *EDDSADGRound1Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EDDSADGRound1Message.Unmarshal(m, b)
}
func (m *EDDSADGRound1Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EDDSADGRound1Message.Marshal(b, m, deterministic)
}
func (m *EDDSADGRound1Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EDDSADGRound1Message.Merge(m, src)
}
func (m *EDDSADGRound1Message) XXX_Size() int {
	return xxx_messageInfo_EDDSADGRound1Message.Size(m)
}
func (m *EDDSADGRound1Message) XXX_DiscardUnknown() {
	xxx_messageInfo_EDDSADGRound1Message.DiscardUnknown(m)
}

var xxx_messageInfo_EDDSADGRound1Message proto.InternalMessageInfo

func (m *EDDSADGRound1Message) GetEddsaPubX() []byte {
	if m != nil {
		return m.EddsaPubX
	}
	return nil
}

func (m *EDDSADGRound1Message) GetEddsaPubY() []byte {
	if m != nil {
		return m.EddsaPubY
	}
	return nil
}

func (m *EDDSADGRound1Message) GetVCommitment() []byte {
	if m != nil {
		return m.VCommitment
	}
	return nil
}

//
// The Round 2 "ACK" is broadcast to peers of the Old Committee in this message.
type EDDSADGRound2Message struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EDDSADGRound2Message) Reset()         { *m = EDDSADGRound2Message{} }
func (m *EDDSADGRound2Message) String() string { return proto.CompactTextString(m) }
func (*EDDSADGRound2Message) ProtoMessage()    {}
func (*EDDSADGRound2Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd99ebe69a0b0962, []int{1}
}

func (m *EDDSADGRound2Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EDDSADGRound2Message.Unmarshal(m, b)
}
func (m *EDDSADGRound2Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EDDSADGRound2Message.Marshal(b, m, deterministic)
}
func (m *EDDSADGRound2Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EDDSADGRound2Message.Merge(m, src)
}
func (m *EDDSADGRound2Message) XXX_Size() int {
	return xxx_messageInfo_EDDSADGRound2Message.Size(m)
}
func (m *EDDSADGRound2Message) XXX_DiscardUnknown() {
	xxx_messageInfo_EDDSADGRound2Message.DiscardUnknown(m)
}

var xxx_messageInfo_EDDSADGRound2Message proto.InternalMessageInfo

//
// The Round 3 data is sent to peers of the New Committee in this message.
type EDDSADGRound3Message1 struct {
	Share                []byte   `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EDDSADGRound3Message1) Reset()         { *m = EDDSADGRound3Message1{} }
func (m *EDDSADGRound3Message1) String() string { return proto.CompactTextString(m) }
func (*EDDSADGRound3Message1) ProtoMessage()    {}
func (*EDDSADGRound3Message1) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd99ebe69a0b0962, []int{2}
}

func (m *EDDSADGRound3Message1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EDDSADGRound3Message1.Unmarshal(m, b)
}
func (m *EDDSADGRound3Message1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EDDSADGRound3Message1.Marshal(b, m, deterministic)
}
func (m *EDDSADGRound3Message1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EDDSADGRound3Message1.Merge(m, src)
}
func (m *EDDSADGRound3Message1) XXX_Size() int {
	return xxx_messageInfo_EDDSADGRound3Message1.Size(m)
}
func (m *EDDSADGRound3Message1) XXX_DiscardUnknown() {
	xxx_messageInfo_EDDSADGRound3Message1.DiscardUnknown(m)
}

var xxx_messageInfo_EDDSADGRound3Message1 proto.InternalMessageInfo

func (m *EDDSADGRound3Message1) GetShare() []byte {
	if m != nil {
		return m.Share
	}
	return nil
}

//
// The Round 3 data is broadcast to peers of the New Committee in this message.
type EDDSADGRound3Message2 struct {
	VDecommitment        [][]byte `protobuf:"bytes,1,rep,name=v_decommitment,json=vDecommitment,proto3" json:"v_decommitment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EDDSADGRound3Message2) Reset()         { *m = EDDSADGRound3Message2{} }
func (m *EDDSADGRound3Message2) String() string { return proto.CompactTextString(m) }
func (*EDDSADGRound3Message2) ProtoMessage()    {}
func (*EDDSADGRound3Message2) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd99ebe69a0b0962, []int{3}
}

func (m *EDDSADGRound3Message2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EDDSADGRound3Message2.Unmarshal(m, b)
}
func (m *EDDSADGRound3Message2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EDDSADGRound3Message2.Marshal(b, m, deterministic)
}
func (m *EDDSADGRound3Message2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EDDSADGRound3Message2.Merge(m, src)
}
func (m *EDDSADGRound3Message2) XXX_Size() int {
	return xxx_messageInfo_EDDSADGRound3Message2.Size(m)
}
func (m *EDDSADGRound3Message2) XXX_DiscardUnknown() {
	xxx_messageInfo_EDDSADGRound3Message2.DiscardUnknown(m)
}

var xxx_messageInfo_EDDSADGRound3Message2 proto.InternalMessageInfo

func (m *EDDSADGRound3Message2) GetVDecommitment() [][]byte {
	if m != nil {
		return m.VDecommitment
	}
	return nil
}

//
// The Round 4 "ACK" is broadcast to peers of the Old and New Committees from the New Committee in this message.
type EDDSADGRound4Message struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EDDSADGRound4Message) Reset()         { *m = EDDSADGRound4Message{} }
func (m *EDDSADGRound4Message) String() string { return proto.CompactTextString(m) }
func (*EDDSADGRound4Message) ProtoMessage()    {}
func (*EDDSADGRound4Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd99ebe69a0b0962, []int{4}
}

func (m *EDDSADGRound4Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EDDSADGRound4Message.Unmarshal(m, b)
}
func (m *EDDSADGRound4Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EDDSADGRound4Message.Marshal(b, m, deterministic)
}
func (m *EDDSADGRound4Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EDDSADGRound4Message.Merge(m, src)
}
func (m *EDDSADGRound4Message) XXX_Size() int {
	return xxx_messageInfo_EDDSADGRound4Message.Size(m)
}
func (m *EDDSADGRound4Message) XXX_DiscardUnknown() {
	xxx_messageInfo_EDDSADGRound4Message.DiscardUnknown(m)
}

var xxx_messageInfo_EDDSADGRound4Message proto.InternalMessageInfo

func init() {
	proto.RegisterType((*EDDSADGRound1Message)(nil), "EDDSADGRound1Message")
	proto.RegisterType((*EDDSADGRound2Message)(nil), "EDDSADGRound2Message")
	proto.RegisterType((*EDDSADGRound3Message1)(nil), "EDDSADGRound3Message1")
	proto.RegisterType((*EDDSADGRound3Message2)(nil), "EDDSADGRound3Message2")
	proto.RegisterType((*EDDSADGRound4Message)(nil), "EDDSADGRound4Message")
}

func init() {
	proto.RegisterFile("protob/eddsa-resharing.proto", fileDescriptor_cd99ebe69a0b0962)
}

var fileDescriptor_cd99ebe69a0b0962 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xd2, 0x4f, 0x4d, 0x49, 0x29, 0x4e, 0xd4, 0x2d, 0x4a, 0x2d, 0xce, 0x48, 0x2c, 0xca,
	0xcc, 0x4b, 0xd7, 0x03, 0x0b, 0x2b, 0x55, 0x72, 0x89, 0xb8, 0xba, 0xb8, 0x04, 0x3b, 0xba, 0xb8,
	0x07, 0xe5, 0x97, 0xe6, 0xa5, 0x18, 0xfa, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x0a, 0xc9, 0x71,
	0x71, 0x83, 0x35, 0xc4, 0x17, 0x94, 0x26, 0xc5, 0x57, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04,
	0x71, 0x82, 0x85, 0x02, 0x4a, 0x93, 0x22, 0x50, 0xe5, 0x2b, 0x25, 0x98, 0x50, 0xe5, 0x23, 0x85,
	0x14, 0xb9, 0x78, 0xca, 0xe2, 0x93, 0xf3, 0x73, 0x73, 0x33, 0x4b, 0x72, 0x53, 0xf3, 0x4a, 0x24,
	0x98, 0xc1, 0x0a, 0xb8, 0xcb, 0x9c, 0xe1, 0x42, 0x4a, 0x62, 0xa8, 0x56, 0x1b, 0x41, 0xad, 0x56,
	0xd2, 0xe5, 0x12, 0x45, 0x16, 0x37, 0x86, 0x8a, 0x1b, 0x0a, 0x89, 0x70, 0xb1, 0x82, 0x1c, 0x9f,
	0x0a, 0x75, 0x0d, 0x84, 0xa3, 0x64, 0x87, 0x5d, 0xb9, 0x91, 0x90, 0x2a, 0x17, 0x5f, 0x59, 0x7c,
	0x4a, 0x2a, 0x92, 0x23, 0x18, 0x15, 0x98, 0x35, 0x78, 0x82, 0x78, 0xcb, 0x5c, 0x90, 0x04, 0xd1,
	0x9d, 0x61, 0x02, 0xd5, 0xef, 0x24, 0x18, 0xc5, 0x0f, 0xf6, 0x8e, 0x3e, 0x3c, 0xc8, 0x92, 0xd8,
	0xc0, 0x61, 0x66, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x92, 0x77, 0xc0, 0x20, 0x53, 0x01, 0x00,
	0x00,
}
